version: '4'

services:

  page:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./page:/usr/share/nginx/html

  proxy_reverse:
    container_name: proxy_reverse
    hostname: proxy_reverse
    image: nginx:1.25
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sublate
    ports:
      - "9999:9999"
    depends_on:
      - api

  api:
    container_name: app1
    hostname: app1
    image: python:slim
    environment:
      - PYTHONPATH=/app
    command: 
      - "sh"
      - "-c"
      - |
        pip install -r /app/requirements.txt
        uvicorn app.main:app --host 0.0.0.0 --port 80 --workers 1 --timeout-keep-alive 65
    volumes:
      - ./:/app
    networks:
      - sublate
    expose:
      - "80"
    depends_on:
      - postgres
      - queue

  worker:
    container_name: worker
    hostname: worker
    image: python:slim
    environment:
      - PYTHONPATH=/app
    command: 
      - "sh"
      - "-c"
      - |
        pip install -r /app/requirements.txt
        celery -A app.worker worker --concurrency 2 --loglevel=debug
    volumes:
      - ./:/app
    networks:
      - sublate
    depends_on:
      - postgres
      - queue

  queue:
    container_name: queue
    hostname: queue
    image: rabbitmq:management
    networks:
      - sublate
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: sublate
      POSTGRES_PASSWORD: DaorMaelon
      POSTGRES_DB: api
    networks:
      - sublate
    ports:
      - "5432:5432"

networks:
  sublate:
    driver: bridge
